spring.application.name=marketplace-auth-service

server.port=8080

server.servlet.context-path=/auth

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.access=read-only