spring.application.name=marketplace-notification-service

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.access=read-only

server.port=8080

server.servlet.context-path=/notifications