services:
  config-server:
    build: ./config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./config:/config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=file:/config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
    networks:
      - marketplace-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - marketplace-network

  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${USER_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=http://config-server:${CONFIG_SERVER_PORT}
    depends_on:
      - postgres
      - config-server
    networks:
      - marketplace-network

  product-service:
    build: ./product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${PRODUCT_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=http://config-server:${CONFIG_SERVER_PORT}
    depends_on:
      - postgres
      - config-server
    networks:
      - marketplace-network

  order-service:
    build: ./order-service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${ORDER_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=http://config-server:${CONFIG_SERVER_PORT}
    depends_on:
      - postgres
      - config-server
    networks:
      - marketplace-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - marketplace-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      config-server:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_started
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - marketplace-network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - marketplace-network

  prometheus:
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-gateway
      - keycloak
      - user-service
      - product-service
      - order-service
    networks:
      - marketplace-network

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    networks:
      - marketplace-network

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "${PGADMIN_PORT}:80"
#    depends_on:
#      - postgres
#    networks:
#      - marketplace-network

networks:
  marketplace-network:
    driver: bridge