spring.application.name=marketplace-api-gateway

management.endpoints.web.exposure.include=health,info,prometheus,gateway
management.endpoint.prometheus.access=read_only
management.endpoint.health.show-details=always

server.port=8080

spring.config.import=optional:configserver:
spring.cloud.config.uri=${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/marketplace
