spring.application.name=marketplace-payment-service

management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.endpoint.prometheus.access=read-only

server.port=8080

server.servlet.context-path=/payments